# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

reviews:
  auto_review:
    enabled: true
    drafts: true  # Enable reviews on draft PRs
    base_branches: ['.*']  # Enable reviews on all branches except the default
