// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqZabvddOezyoavSNEBUljfGJA51zzvgM',
    appId: '1:630572846233:web:27302a9a6cc10eb5be7c08',
    messagingSenderId: '630572846233',
    projectId: 'exono-ad7a4',
    authDomain: 'exono-ad7a4.firebaseapp.com',
    storageBucket: 'exono-ad7a4.firebasestorage.app',
    measurementId: 'G-P9LV7FDWF0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgIIV64Wj8fs7mEyazSsWFi6Cj0cDpYL0',
    appId: '1:630572846233:android:9306e8feee1c17ffbe7c08',
    messagingSenderId: '630572846233',
    projectId: 'exono-ad7a4',
    storageBucket: 'exono-ad7a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVvvtLqyiB74dKGJRPigTHJGobaYjkrgo',
    appId: '1:630572846233:ios:36de58a3193ebb3cbe7c08',
    messagingSenderId: '630572846233',
    projectId: 'exono-ad7a4',
    storageBucket: 'exono-ad7a4.firebasestorage.app',
    iosBundleId: 'com.example.exono',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVvvtLqyiB74dKGJRPigTHJGobaYjkrgo',
    appId: '1:630572846233:ios:36de58a3193ebb3cbe7c08',
    messagingSenderId: '630572846233',
    projectId: 'exono-ad7a4',
    storageBucket: 'exono-ad7a4.firebasestorage.app',
    iosBundleId: 'com.example.exono',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqZabvddOezyoavSNEBUljfGJA51zzvgM',
    appId: '1:630572846233:web:9464afb876cbe20cbe7c08',
    messagingSenderId: '630572846233',
    projectId: 'exono-ad7a4',
    authDomain: 'exono-ad7a4.firebaseapp.com',
    storageBucket: 'exono-ad7a4.firebasestorage.app',
    measurementId: 'G-WWQ1V57D27',
  );
}
